# Generated by Django 5.2.4 on 2025-07-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_doctordetail_available_timeslots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
