# Generated by Django 5.2.4 on 2025-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_doctorschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
