# Generated by Django 5.2.4 on 2025-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_doctorschedule_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordetail",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctordetail",
            name="specialization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
