# Generated by Django 5.2.4 on 2025-07-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_doctordetail_location_doctordetail_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
